### ISSUE TITLE
Look at Hast.me

### ISSUE THREAD

**Issue by Slava** [jacksingleton/hacker-slides#10]
Hey there, 

I think hast.me is a very similar app that already has a lot of features you listed in the README.md:

- built with Meteor
- collaborative
- has auth
- similar editor

https://github.com/zhouzhuojie/hast

**Comment by jacksingleton** [comment]
Thanks for pointing this out, I've decided to continue maintaining hacker-slides as a big reason for me creating it was to familiarize myself with Sandstorm.

I would definitely encourage everyone to check out hast though.

**Comment by ocdtrekkie** [comment]
As a Meteor app, it'd probably be really easy to port Hast.me to Sandstorm with meteor-spk, but I don't really want to have to maintain it. A Sandstorm app maintained by it's developer (Like @jacksingleton maintains this app) is better than a Sandstorm app which has to have a separate person maintaining a port. (If @zhouzhuojie wanted to maintain a Sandstorm port, then folks would have two options for slides on Sandstorm, mind you.)
