### ISSUE TITLE
€ not supported

### ISSUE THREAD

**Issue by thunfischbrot** [jacksingleton/hacker-slides#11]
Whenever a €-sign shows up the preview states

    ERROR: The attempt to fetch ../slides.md failed with HTTP status 500.Check your browser's JavaScript console for more details.
    Remember that you need to serve the presentation HTML from a HTTP server.

**Comment by JamborJan** [comment]
Same with German "Umlaute" ä, ö, ü and the ß which are quite important. Other special signs like ∂∑Ωø cause the same error.

![bildschirmfoto 2015-02-18 um 15 06 04](https://cloud.githubusercontent.com/assets/7508960/6248415/b1d22ae8-b77f-11e4-8089-cb9c0459deaf.png)

**Comment by jacksingleton** [comment]
Ooh encoding, will look at this soon. Thanks for adding the issue!

**Comment by jacksingleton** [comment]
Fixed by 75cf0f3cc961ad2db430d209a59f4d1a87cb2c19
