### ISSUE TITLE
Public sharing

### ISSUE THREAD

**Issue by JamborJan** [jacksingleton/hacker-slides#13]
Is it possible to share a slide publicly?

When I'm not logged in, I see this error:

```
Error: Unauthorized [403]
    at Proxy.makeContext (app/server/proxy.js:951:13)
    at app/server/proxy.js:1191:17
    at C (/node_modules/es6-promise.js:12:57)
    at /node_modules/es6-promise.js:17:252
    at t (/node_modules/es6-promise.js:9:473)
    at process._tickCallback (node.js:419:13)
```

**Comment by jacksingleton** [comment]
Interesting, you can share the grain url (the url before you enter present mode), but note if you share that url people will be able to edit your presentation.

The plan is to only allow the owning Sandstorm account to edit, and let everyone else view. But they would still have to follow the grain link and then click present themselves.

I think fixing this is dependent on the app being able to open fullscreen mode without breaking out of the sandstorm shell, which is currently how present mode works.
