### ISSUE TITLE
publish a presentation to share a read-only view

### ISSUE THREAD

**Issue by jacksingleton** [jacksingleton/hacker-slides#16]
- use sandstorm web publishing api
- maybe use a non-guessable URL to provide access-with-the-link style sharing

**Comment by ocdtrekkie** [comment]
The web publishing API creates a non-guessable URL by default. :)

**Comment by jacksingleton** [comment]
Ah perfect

**Comment by ocdtrekkie** [comment]
Sandstorm has just added a new sharing model which supports generating links to content with different access levels. Etherpad and a couple of other apps now support it.

I did a talk last weekend with a Hacker Slides presentation, and I want to post the link, but only if I can get a read-only sharing link for it.

**Comment by jacksingleton** [comment]
Thanks for the heads up! Yeah I noticed the behavior changed from letting anyone edit if the document url was shared to just locking everyone out.

**Comment by JonTheNiceGuy** [comment]
As I used HackerSlides at Oggcamp this weekend, and I'm now being asked to share my presentations, is their either a shortcut to get the files out, or failing that, something I can use to republish?

**Comment by jacksingleton** [comment]
Hey Jon - not really right now.

Another thing you can do is use the sandstorm "Download Backup" button. That will give you a zip file with a data directory containing a file called `slides.md`

Then clone RevealJS, and follow the external markdown instructions (using slides.md as your markdown file): https://github.com/hakimel/reveal.js#external-markdown

You'll want a slides section like this:
<section data-markdown="../slides.md" data-separator="^-( *)-( *)-( *-*)*" data-separator-notes="^Note:" data-charset="utf-8"></section>

So... that's also a bit messy I now. But it /is/ *Hacker* slides right ;)

But seriously, I'm going to give this app some love this weekend to make it more approachable for contributors and I think @zarvox may even hack out this feature.

**Comment by zarvox** [comment]
FWIW, this is fixed in 0.2.0 - the "Present" mode opens a window to the static-publishing URL.  If you need to extract the markdown from a published presentation, you can grab it from `http://<your-random-publishing-domain>/slides.md`

Cheers!
