### ISSUE TITLE
Some quotation marks not supported.

### ISSUE THREAD

**Issue by ocdtrekkie** [jacksingleton/hacker-slides#22]
Copy-pasting the following into your app freaks out the preview pane:

`“if you want a definition of the term ‘walled garden’ as it pertains to technology, ask a man with both an iphone and a chromebook” - @malki`

This appears to be because the quotes (single and double) are angled, a common Office/PowerPoint tendency.

**Comment by jacksingleton** [comment]
thanks for opening the issue! those quotes are unicode code points, which I added support for in master a week or so ago but I haven't tagged a new release yet.

I'm closing now as I'm 95% sure this is fixed on master. Let me know if this doesn't fix the problem!

**Comment by jacksingleton** [comment]
Related: https://github.com/jacksingleton/hacker-slides/issues/11

**Comment by ocdtrekkie** [comment]
Sorry, I forgot I haven't had an update for Hacker Slides since the other character-related issues were fixed.
