### ISSUE TITLE
Use of unicode character crashes preview pane

### ISSUE THREAD

**Issue by jadeqwang** [jacksingleton/hacker-slides#24]
If I try to paste in, say, a unicode arrow (→) into my slide to replace "->", [the preview pane shows an error](https://www.evernote.com/shard/s59/sh/b8d27061-cb1e-4445-875e-1347be0f8a45/749b0dc232fd92d218aa6c79f37b27c3/deep/0/Progress,-Technology,-Culture---Sandstorm.png):

![](https://www.evernote.com/shard/s59/sh/b8d27061-cb1e-4445-875e-1347be0f8a45/749b0dc232fd92d218aa6c79f37b27c3/deep/0/Progress,-Technology,-Culture---Sandstorm.png)

I tried it with a couple other unicode arrows and got the same result, and suspect this may be the behavior with any unicode character.

**Comment by ocdtrekkie** [comment]
This should already be fixed but Jack has not updated the app.

**Comment by jacksingleton** [comment]
yeah I should probably update it at some point :)

but thanks for reporting it!
