### ISSUE TITLE
Presentation preview doesn't show when Sandstorm navbar is visible

### ISSUE THREAD

**Issue by ocdtrekkie** [jacksingleton/hacker-slides#31]
This issue is created by the new UI on Sandstorm. When the navbar (New/Open) is open, the presentation side of the Hacker Slides UI is blank.

**Comment by jacksingleton** [comment]
Oh thanks, I didn't notice that.

Might be able to get to it this weekend.

**Comment by jacksingleton** [comment]
@ocdtrekkie I can't reproduce this in chromium or firefox. do you still see the problem?

**Comment by ocdtrekkie** [comment]
Appears whatever caused it was fixed by platform changes in the last two months. Tested working on both Firefox and Edge, the two browsers I use.
