### ISSUE TITLE
I now have a song stuck in my head.

### ISSUE THREAD

**Issue by frenchi** [jacksingleton/hacker-slides#32]
Steps to reproduce:

1. https://www.youtube.com/watch?v=y6120QOlsfU

I'll send a PR to fix it, once I've got the song out of my head.

**Comment by birdsarah** [comment]
I cannot believe I clicked on the link. Now I am also affected by this bug.

**Comment by frenchi** [comment]
Looks like someone else has been able to confirm this bug. Can we get a bug label, and possibly a high priority?

**Comment by jacksingleton** [comment]
Hahaha.

Added appropriate label, PR is welcome!

**Comment by frenchi** [comment]
Closing, as it looks like this bug has resolved itself after listening to this on repeat:
https://www.youtube.com/watch?v=SQoA_wjmE9w
