### ISSUE TITLE
Speaker notes is a 404

### ISSUE THREAD

**Issue by paulproteus** [jacksingleton/hacker-slides#33]
Steps to reproduce:

* Go to https://oasis.sandstorm.io/demo

* Click "Try demo"

* Click "Install..."

* Find Hacker Slides & install it

* Create a new Hacker Slides grain

* Click on the words **HACKER SLIDES**

* Press `s` on the keyboard

Expected behavior:

* See presenter notes.

Actual behavior:

* 404

**Comment by paulproteus** [comment]
@jacksingleton I'm probably willing to look into this bug since it affected me recently.

**Comment by jacksingleton** [comment]
Thanks for reporting (and triple thanks if you do get a chance to look into
it)

I'm 90% sure that it will be a file left out of the new sandstorm-files.list

Jack

**Comment by paulproteus** [comment]
Exactly re: sandstorm-files.list

**Comment by JonTheNiceGuy** [comment]
Affected me. Anything I can do to help?

**Comment by paulproteus** [comment]
Hey all. Let me see if I can figure this out right now.

**Comment by ovizii** [comment]
I'm slightly unsure what this fixed means: so once this app is updated, I'm supposed to get a notification from within sandstorm to update and the bug will be fixed?

**Comment by paulproteus** [comment]
Yup​
