### ISSUE TITLE
change title to 'Hacker Slides' (space) without breaking 'new HackerSlides' button

### ISSUE THREAD

**Issue by jacksingleton** [jacksingleton/hacker-slides#9]

**Comment by jacksingleton** [comment]
Asheesh:

    You possibly need "New Hacker Slides presentation".

    There's some crazy code called actionNameToAppName (or similar) in Sandstorm that is hopefully going away soon; the upshot is it eats the last word.

**Comment by ocdtrekkie** [comment]
The appName field was just added to the pkgdef template a few days ago. So with the next release, it should be possible to have two word app names. (Though if anyone is using an older version of Sandstorm, they would get the appName as "Hacker", until they updated.)

**Comment by jacksingleton** [comment]
Cool! Thanks. I'll probably just specify the appName then.
